name: Revanced X10NDED

on:
  push:
    branches:
      - main

jobs:
  update-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Verify Java version
        run: java -version
      - name: Revanced extended pre build packages Download
        run: |
          mkdir -p packages
          curl -sL https://github.com/inotia00/revanced-cli/releases/latest/download/revanced-cli-all.jar -o packages/revanced-cli-all.jar
          curl -sL https://github.com/inotia00/revanced-patches/releases/latest/download/revanced-patches.jar -o packages/revanced-patches.jar
          curl -sL https://github.com/inotia00/revanced-integrations/releases/latest/download/app-release-unsigned.apk -o packages/app-release-unsigned.apk
         
      - name: Download YouTube APK
        run: |
          wget -q https://framagit.org/tuxicoman/googleplaydownloader/-/jobs/artifacts/master/download?job=master -O googleplaydownloader.zip
          unzip -q googleplaydownloader.zip
          cd googleplaydownloader || exit
          chmod +x googleplaydownloader.py
          ./googleplaydownloader.py --package com.google.android.youtube --arch all -o youtube.zip
          unzip -q youtube.zip -d youtube
          mv youtube/*.apk ../youtube.apk

      - name: Build ROOT and NON ROOT APKs
        run: |
          java -jar packages/revanced-cli-all.jar -a youtube.apk -o revanced_root.apk -m packages/app-release-unsigned.apk -b packages/revanced-patches.jar -e microg-support -e spoof-app-version -e enable-old-quality-layout -e custom-branding-name -e custom-branding-icon-revancify -e custom-branding-icon-mmt -e custom-branding-icon-manual -e custom-branding-icon-afn-red -e custom-branding-icon-afn-blue -c
          java -jar packages/revanced-cli-all.jar -a youtube.apk -o revanced_non_root.apk -m packages/app-release-unsigned.apk -b packages/revanced-patches.jar -i microg-support -e spoof-app-version -e enable-old-quality-layout -e custom-branding-name -e custom-branding-icon-revancify -e custom-branding-icon-mmt -e custom-branding-icon-manual -e custom-branding-icon-afn-red -e custom-branding-icon-afn-blue -c
      - name: Create Release with APKs and Information
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Revanced APKs
            *ROOT:* revanced_root.apk
